# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RExp-e8SjoU0r65YAZ5ptDrNn9uA9GeT
"""

import pandas as pd

df = pd.read_csv('/content/Salary Data.csv')

df

df.isnull().sum()

for col in ['Age', 'Years of Experience', 'Salary']:
    df[col] = df[col].fillna(df[col].mean())

for col in ['Gender', 'Education Level', 'Job Title']:
    df[col] = df[col].fillna(df[col].mode()[0])

"""### Null values after imputation:"""

df.isnull().sum()

"""### Applying Label Encoding to Categorical Columns"""

from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for column in ['Gender', 'Education Level', 'Job Title']:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

display(df.head())
display(df.info())

"""### Separating Input Features and Target Variable"""

X = df.drop('Salary', axis=1)
y = df['Salary']

print('Input Features (X) head:')
display(X.head())
print('\nTarget Variable (y) head:')
display(y.head())

"""### Splitting Data into Training and Testing Sets"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'Shape of X_train: {X_train.shape}')
print(f'Shape of X_test: {X_test.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

"""### Model Training and Evaluation"""

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

results = {}

# 1. Linear Regression
print('Training Linear Regression...')
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
y_pred_lin_reg = lin_reg.predict(X_test)
mae_lin_reg = mean_absolute_error(y_test, y_pred_lin_reg)
r2_lin_reg = r2_score(y_test, y_pred_lin_reg)
results['Linear Regression'] = {'MAE': mae_lin_reg, 'R2': r2_lin_reg}
print(f'Linear Regression - MAE: {mae_lin_reg:.2f}, R2: {r2_lin_reg:.2f}')

# 2. K-Nearest Neighbors (KNN) Regressor
print('\nTraining K-Nearest Neighbors...')
knn_reg = KNeighborsRegressor(n_neighbors=5) # Using 5 neighbors as a common starting point
knn_reg.fit(X_train, y_train)
y_pred_knn = knn_reg.predict(X_test)
mae_knn = mean_absolute_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)
results['KNN Regressor'] = {'MAE': mae_knn, 'R2': r2_knn}
print(f'KNN Regressor - MAE: {mae_knn:.2f}, R2: {r2_knn:.2f}')

# 3. Support Vector Machine (SVM) Regressor
print('\nTraining Support Vector Machine...')
# Using a linear kernel for simplicity, can be tuned to 'rbf' etc.
svm_reg = SVR(kernel='linear')
svm_reg.fit(X_train, y_train)
y_pred_svm = svm_reg.predict(X_test)
mae_svm = mean_absolute_error(y_test, y_pred_svm)
r2_svm = r2_score(y_test, y_pred_svm)
results['SVM Regressor'] = {'MAE': mae_svm, 'R2': r2_svm}
print(f'SVM Regressor - MAE: {mae_svm:.2f}, R2: {r2_svm:.2f}')

# 4. Decision Tree Regressor
print('\nTraining Decision Tree Regressor...')
dt_reg = DecisionTreeRegressor(random_state=42)
dt_reg.fit(X_train, y_train)
y_pred_dt = dt_reg.predict(X_test)
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)
results['Decision Tree Regressor'] = {'MAE': mae_dt, 'R2': r2_dt}
print(f'Decision Tree Regressor - MAE: {mae_dt:.2f}, R2: {r2_dt:.2f}')

# 5. Random Forest Regressor
print('\nTraining Random Forest Regressor...')
rf_reg = RandomForestRegressor(n_estimators=100, random_state=42) # Using 100 estimators as a common starting point
rf_reg.fit(X_train, y_train)
y_pred_rf = rf_reg.predict(X_test)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)
results['Random Forest Regressor'] = {'MAE': mae_rf, 'R2': r2_rf}
print(f'Random Forest Regressor - MAE: {mae_rf:.2f}, R2: {r2_rf:.2f}')

"""### Note on Naive Bayes for Regression

Naive Bayes algorithms (like Gaussian Naive Bayes) are fundamentally designed for **classification** tasks, where the goal is to predict a discrete class label. They are based on Bayes' theorem with strong independence assumptions between features.

While some adaptations exist to use Naive Bayes for regression (e.g., by treating the output as a discretized variable or by modeling the conditional distribution of a continuous target), it is **not a standard or typically recommended approach** for predicting continuous values like 'Salary'. Standard regression models (like Linear Regression, Decision Trees, Random Forests, SVMs, or KNNs) are generally more appropriate and perform better for such tasks.

Therefore, we are not directly implementing a Naive Bayes model for regression in this context, focusing instead on the widely used regression algorithms.

### Summary of Model Performance
"""

import pandas as pd

results_df = pd.DataFrame(results).T
display(results_df.sort_values(by='R2', ascending=False))

"""### Visual Comparison of Model Performance"""

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
plot_data = {
    'Actual': y_test,
    'Linear Regression': y_pred_lin_reg,
    'KNN Regressor': y_pred_knn,
    'SVM Regressor': y_pred_svm,
    'Decision Tree Regressor': y_pred_dt,
    'Random Forest Regressor': y_pred_rf
}

# Create a figure with subplots
fig, axes = plt.subplots(2, 3, figsize=(20, 12))
axes = axes.flatten() # Flatten the 2x3 array of axes for easy iteration

model_names = ['Linear Regression', 'KNN Regressor', 'SVM Regressor', 'Decision Tree Regressor', 'Random Forest Regressor']

for i, model_name in enumerate(model_names):
    sns.scatterplot(x=plot_data['Actual'], y=plot_data[model_name], ax=axes[i], alpha=0.6)
    axes[i].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Ideal prediction line
    axes[i].set_title(f'{model_name} (R2: {results[model_name]["R2"]:.2f})')
    axes[i].set_xlabel('Actual Salary')
    axes[i].set_ylabel('Predicted Salary')
    axes[i].grid(True, linestyle='--', alpha=0.7)

# Remove any unused subplots if the number of models is not exactly 6
if len(model_names) < len(axes):
    for j in range(len(model_names), len(axes)):
        fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""### Bar Graph Comparison of Model Performance Metrics"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a figure with two subplots for R2 and MAE
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# Plotting R2 Scores
sns.barplot(x=results_df.index, y='R2', data=results_df.sort_values(by='R2', ascending=False), ax=axes[0], palette='viridis')
axes[0].set_title('Model R2 Scores Comparison')
axes[0].set_xlabel('Model')
axes[0].set_ylabel('R2 Score')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(axis='y', linestyle='--', alpha=0.7)

# Plotting MAE Scores
sns.barplot(x=results_df.index, y='MAE', data=results_df.sort_values(by='MAE', ascending=True), ax=axes[1], palette='plasma')
axes[1].set_title('Model Mean Absolute Error (MAE) Comparison')
axes[1].set_xlabel('Model')
axes[1].set_ylabel('Mean Absolute Error (MAE)')
axes[1].tick_params(axis='x', rotation=45)
axes[1].grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

import pickle
from google.colab import files

# Identify the best model (Random Forest Regressor in this case)
best_model = rf_reg
model_filename = 'random_forest_regressor.pkl'

# Save the model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Best model saved as {model_filename}")

# Provide a download link for the user
files.download(model_filename)

"""### Step 1: Create a Streamlit Application File (`app.py`)

First, you need to create a Python file (e.g., `app.py`) that will serve as your Streamlit application. This file will load the saved model and provide a user interface for making predictions. Here's the code you can use. Copy and paste this into a new file named `app.py`.
"""

import streamlit as st
import pandas as pd
import pickle

# --- 1. Load the trained model ---
# The model will be loaded from the 'random_forest_regressor.pkl' file
# Make sure this file is in the same directory as your app.py on Streamlit Cloud

try:
    with open('random_forest_regressor.pkl', 'rb') as file:
        model = pickle.load(file)
    st.success("Model loaded successfully!")
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop() # Stop the app if the model can't be loaded

# --- 2. Streamlit UI ---
st.title('Salary Prediction App')
st.write('Enter the details below to predict the salary.')

# Input fields for user
age = st.slider('Age', 18, 65, 30)
gender = st.selectbox('Gender', ['Male', 'Female'])
education_level = st.selectbox('Education Level', ["Bachelor's", "Master's", 'PhD'])
job_title = st.text_input('Job Title', 'Software Engineer')
years_of_experience = st.slider('Years of Experience', 0, 40, 5)

# --- 3. Preprocessing User Input ---
# The model was trained on label-encoded categorical features.
# We need to apply the same encoding to user input.
# For simplicity, we'll use predefined mappings based on the original LabelEncoder.
# In a real-world scenario, you'd save/load the LabelEncoder objects.

# Manual mapping for gender (assuming 0 for Female, 1 for Male based on original training)
gender_encoded = 1 if gender == 'Male' else 0

# Manual mapping for education level (based on original training)
education_mapping = {"Bachelor's": 0, "Master's": 1, 'PhD': 2}
education_encoded = education_mapping.get(education_level, 0) # Default to Bachelor's if not found

# For Job Title, this is more complex as LabelEncoder assigns a unique int to each string.
# For demonstration, we'll assign a placeholder or require exact match to known titles.
# In a production app, you'd have a mapping or use a more robust encoding strategy (e.g., one-hot).
# For now, let's just use the length of the string as a very basic placeholder for demonstration.
# A better approach would be to have a list of all job titles encountered during training and map to their index.
# For this example, let's assume we have `label_encoders['Job Title']` available if it were saved.
# Since we don't have it directly here, we'll simulate a simple encoding. **THIS PART NEEDS CAREFUL CONSIDERATION IN A REAL DEPLOYMENT**
# For now, let's just create a dummy mapping for the job title.

# NOTE: In a full deployment, you should save the actual `label_encoders` objects
# and load them here to ensure consistent encoding.
# For this example, we'll just use a placeholder for Job Title encoding.

# Example placeholder for job_title encoding (needs refinement for actual use)
# If you saved the `label_encoders` dict, you would use:
# job_title_encoded = label_encoders['Job Title'].transform([job_title])[0] if job_title in label_encoders['Job Title'].classes_ else -1
# For now, let's use a simple hash or a default value for demonstration.

# To make this runnable without the original LabelEncoder, let's create a dummy job_title_encoded.
# In a real app, you MUST ensure consistency with training time encoding.
# For this example, let's just assign a fixed value or use a simple length for demo purposes

# A more robust solution for Job Title would involve saving the LabelEncoder itself
# along with the model and loading it here.

# For the purpose of this example, we will assign a dummy value for the job title.
# In a real scenario, you'd have to ensure consistent encoding with the training data.
# As we don't have the full `label_encoders` object saved, we'll use a placeholder.
# Let's assume 'Software Engineer' was encoded as 159, as per the `X` DataFrame head.
job_title_encoded = 159 # Placeholder for 'Software Engineer', needs proper mapping for other titles

# If you have a list of all trained job titles, you can do something like:
# known_job_titles = [...] # Load this from a file or directly from your training data
# if job_title in known_job_titles:
#    job_title_encoded = known_job_titles.index(job_title)
# else:
#    job_title_encoded = len(known_job_titles) # or some default/unknown value

# Create a DataFrame for prediction
input_data = pd.DataFrame([[age, gender_encoded, education_encoded, job_title_encoded, years_of_experience]],
                            columns=['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience'])

# --- 4. Make Prediction ---
if st.button('Predict Salary'):
    prediction = model.predict(input_data)[0]
    st.success(f'Predicted Salary: ${prediction:,.2f}')

"""### Step 2: Create a `requirements.txt` File

Streamlit Cloud needs to know which Python libraries your application depends on. Create a file named `requirements.txt` in the same directory as `app.py` and add the following contents:
"""

streamlit
pandas
scikit-learn # For the Random Forest Regressor

from google.colab import files

requirements_content = """streamlit
pandas
scikit-learn
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements_content)

print("requirements.txt has been created.")
files.download('requirements.txt')

"""### Step 3: Set up a GitHub Repository

1.  **Create a new GitHub repository:** Go to [GitHub](https://github.com/) and create a new public repository.
2.  **Upload your files:** Upload the `app.py`, `requirements.txt`, and your saved model file (`random_forest_regressor.pkl`) to this new GitHub repository. Ensure all three files are in the root directory of the repository.

### Step 4: Deploy to Streamlit Cloud

1.  **Go to Streamlit Cloud:** Navigate to [Streamlit Cloud](https://share.streamlit.io/) and log in.
2.  **Click 'New app':** You'll see an option to deploy a new app.
3.  **Connect to GitHub:** Select your GitHub repository where you uploaded the files.
4.  **Configure deployment:**
    *   **Repository:** Select your GitHub repository.
    *   **Branch:** Choose the branch where your files are (usually `main` or `master`).
    *   **Main file path:** Enter `app.py`.
    *   **Python version:** Select a compatible Python version.
5.  **Click 'Deploy!':** Streamlit Cloud will then build and deploy your application. This might take a few minutes.

Once deployed, you'll get a public URL for your Salary Prediction App! Let me know if you encounter any issues during this process.
"""

